apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: default
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: pythons/my-python-app:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: APP_HOST
          valueFrom:
            configMapKeyRef:
              name: python-app-config
              key: APP_HOST
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: python-app-config
              key: APP_PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: python-app-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: "/"
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/"
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
